name: Packaging application

on:
  push:
    branches:
      - main

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Permissions
        run : chmod +x gradlew

      - name: Build linux package
        run: |
          ./gradlew clean
          ./gradlew jpackage

      - name: Upload Linux artifact rpm
        uses: actions/upload-artifact@v4
        with:
          name: linux-package-rpm
          path: build/jpackage/*.rpm

      - name: Upload Linux artifact deb
        uses: actions/upload-artifact@v4
        with:
          name: linux-package-deb
          path: build/jpackage/*.deb

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build windows package
        run: |
          ./gradlew clean
          ./gradlew jpackage

      - name: Upload Windows artifact exe
        uses: actions/upload-artifact@v4
        with:
          name: windows-package-exe
          path: build/jpackage/*.exe

      - name: Upload Windows artifact msi
        uses: actions/upload-artifact@v4
        with:
          name: windows-package-msi
          path: build/jpackage/*.msi

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Permissions
        run: chmod +x gradlew

      - name: Build macos package
        run: |
          ./gradlew clean
          ./gradlew jpackage

      - name: Upload macOS artifact dmg
        uses: actions/upload-artifact@v4
        with:
          name: macos-package-dmg
          path: build/jpackage/*.dmg

      - name: Upload macOS artifact pkg
        uses: actions/upload-artifact@v4
        with:
          name: macos-package-pkg
          path: build/jpackage/*.pkg